### ISSUE TITLE
Add user defined snippets display to snippets tree view

### ISSUE THREAD

**Issue by RandomFractals** [RandomFractals/vscode-snippets-viewer#12]
see: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

**Comment by usernamehw** [comment]
When using https://marketplace.visualstudio.com/items?itemName=svipas.control-snippets to remove all built-in snippets extension shows permanent loading message:

![Screenshot (458)](https://user-images.githubusercontent.com/9638156/112948239-8168de00-9140-11eb-8492-0674b8ad33f0.png)

Maybe it will be different with adding user defined snippets. Or maybe with 0 user snippets it will still be like that.

Extension should remove loading message after reading the files.

**Comment by RandomFractals** [comment]
users snippets in tree view:

![image](https://user-images.githubusercontent.com/656833/113420791-8d96aa80-938f-11eb-9ab8-96eff69470b7.png)
