### ISSUE TITLE
Loading message when all snippets are disabled

### ISSUE THREAD

**Issue by usernamehw** [RandomFractals/vscode-snippets-viewer#36]
When using https://marketplace.visualstudio.com/items?itemName=svipas.control-snippets to remove all built-in snippets extension shows permanent loading message:

![Screenshot (458)](https://user-images.githubusercontent.com/9638156/112948239-8168de00-9140-11eb-8492-0674b8ad33f0.png)

Maybe it will be different with adding user defined snippets. Or maybe with 0 user snippets it will still be like that.

Extension should remove loading message after reading the files.

**Comment by RandomFractals** [comment]
@usernamehw so, you used that extension to remove all installed extension snippets?

That Loading code snippets message is from a Welcome view configured for that tree view.

I'd say this is very unlikely to happen, and will not be showing when I add user-defined and global snippets.

So, if you don't mind, I will close this unlikely issue.
