### ISSUE TITLE
Map javascriptreact and typescriptreact snippets icons to what editor shows in file titlebar

### ISSUE THREAD

**Issue by usernamehw** [RandomFractals/vscode-snippets-viewer#37]
Should they use the same react icons as editors?

![Screenshot (459)](https://user-images.githubusercontent.com/9638156/112950927-80857b80-9143-11eb-8d37-84832eb13640.png)

**Comment by RandomFractals** [comment]
They should. Do you know how to get that react icon from vscode files theme?

**Comment by RandomFractals** [comment]
oh, I believe those file extensions should be `jsx` and `tsx`. I'll remap them.

**Comment by RandomFractals** [comment]
@usernamehw I remaped them. TS react still shows regular TS file icon, but that might look different on your machine depending on vscode files theme you are using.

![image](https://user-images.githubusercontent.com/656833/113011692-a6108600-913f-11eb-9812-31f86bd263e4.png)
