### ISSUE TITLE
Bug loading code snippets... 

### ISSUE THREAD

**Issue by souhailmerroun** [RandomFractals/vscode-snippets-viewer#74]
Hello,

I just installed the extension and it doesn't seem to work. 

![image](https://user-images.githubusercontent.com/8895242/145793913-f49e8365-6ec3-4e5d-8278-d8710f5b605a.png)

Here is my VS

![image](https://user-images.githubusercontent.com/8895242/145794016-4614b0a6-f0ef-4454-b75b-d04ef92a8899.png)

**Comment by souhailmerroun** [comment]
After some testing, it is not working when i open a WSL session. otherwise, it works fine.

https://docs.microsoft.com/en-us/windows/wsl/install
https://code.visualstudio.com/docs/remote/wsl-tutorial

**Comment by RandomFractals** [comment]
This extension was not designed to work with WSL. I don't think I'll be adding that feature.

Thank you for your feedback!
