### ISSUE TITLE
Improving settings understanding with simpler words or providing examples

### ISSUE THREAD

**Issue by souhailmerroun** [RandomFractals/vscode-snippets-viewer#75]
Hello,

I am having a hard time understanding these 3 settings and what they do. Could someone explain me please?

Thanks.

![image](https://user-images.githubusercontent.com/8895242/150627363-69f7e18c-21be-48b5-9077-dfdd0622414e.png)

![image](https://user-images.githubusercontent.com/8895242/150627369-35f7f74c-1080-4e7f-8173-573d656d90a2.png)

![image](https://user-images.githubusercontent.com/8895242/150627374-1e3e5994-1337-4046-b4e2-059b9b76fc0d.png)

**Comment by RandomFractals** [comment]
@souhailmerroun they are all documented in features section:

https://github.com/RandomFractals/vscode-snippets-viewer#features

and Configuration in docs: https://github.com/RandomFractals/vscode-snippets-viewer#configuration

If you try them from the Snippets Tree view, you should be able to see what they do.
