### ISSUE TITLE
python snippets don't show up in snippets viewer

### ISSUE THREAD

**Issue by xsjad0** [RandomFractals/vscode-snippets-viewer#90]
Hi guys,
thanks for the great extension! I'm using snippets a lot and this helps me to inspect & use all my snippets quickly.

The only thing is that I can't see python code snippets

![grafik](https://user-images.githubusercontent.com/34922647/216267366-879ae9e1-9153-4782-a738-c48ad2b07c12.png)

After setting the option "show only active editor language snippets" the python snippets appear

![grafik](https://user-images.githubusercontent.com/34922647/216267668-25e48d19-485f-4b30-9495-a917623425da.png)

but I really like to show all available snippets and just use the "focus on active editor snippets".

Can anyone confirm this behaviour?
I'm using version 1.12.0

Thanks!

**Comment by RandomFractals** [comment]
@xsjad0 you should be able to see custom Python snippets for the extensions you have installed with or without .py editor focus.

![image](https://user-images.githubusercontent.com/656833/220937003-5cfa5392-a1d4-4fb5-97cc-2ccb4d9a46f6.png)
