### ISSUE TITLE
CSS snippets not showing in sidebar

### ISSUE THREAD

**Issue by matthewjrallen** [RandomFractals/vscode-snippets-viewer#92]
I have a css.json file with a css snippet in there but it's not showing in the snippets viewer. Other types are showing. 

<img width="1591" alt="Screenshot 2023-05-24 at 15 37 55" src="https://github.com/RandomFractals/vscode-snippets-viewer/assets/6630880/5d4b07e2-857e-4291-92e9-3f8bbfe17182">

**Comment by smallma** [comment]
same issue, also need scss and json

**Comment by RandomFractals** [comment]
See if you need to toggle snippets viewer settings. Support for user-defined snippets was added in #12.

Also, you should add language to your snippet. See #47 for more info.
